---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginxhello-hr
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: 'false'
spec:
  chart:
    git: https://github.com/EslamSaberSoliman/gitops-nginxhello.git
    path: helm/chart
    ref: master
  rollback:
    enable: true
    retry: true
